---
title: "HS_GCMS_Spectral_Deconvolution"
author: "Angiely Camacho, José Abata, Jefferson Pastuna"
date: "2024-04-12"
output:
  github_document:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
usethis::git_vaccinate()

```

### Introduction

Write an Introduction.

### Before to start

Write a package description.

### eRah package workflow

How to star.

```{r echo=TRUE, message=FALSE, warning=FALSE}

# eRah package installation
#install.packages('erah')
# eRah library call
library(erah)

```

Folder files

```{r echo=TRUE}

# Delete all file that are not in folders
unlink('Data/Data_to_eRah/*')
# Data folder path
createdt('Data/Data_to_eRah/')

```

New experiment.


```{r echo=TRUE}

instrumental <- read.csv('Data/Metadata_to_eRah/HS_GCMS_Data_inst.csv')
phenotype <- read.csv('Data/Metadata_to_eRah/HS_GCMS_Data_pheno.csv')

ex <- newExp(instrumental = instrumental,
             phenotype = phenotype,
             info = 'Amazonia honey')

```

Compound deconvolution

Parameter

```{r echo=TRUE}

ex.dec.par <- setDecPar(min.peak.width = 2,
                        min.peak.height = 450,
                        noise.threshold = 45,
                        avoid.processing.mz = c(30:69,73:75,147:149))

```

parallel processing

```{r echo=TRUE}

plan(future::multisession,
     workers = 16)

```

Deconvolution

```{r echo=TRUE, warning=FALSE}

ex <- deconvolveComp(ex,
                     ex.dec.par)

```

Alignment

```{r echo=TRUE}

# Alignment parameters
ex.al.par <- setAlPar(min.spectra.cor = 0.90,
                      max.time.dist = 3,
                      mz.range = 70:550)
# Alignment
ex <- alignComp(ex,
                alParameters = ex.al.par)

```

Missing compound recovery


```{r echo=TRUE}

ex <- recMissComp(ex,
                  min.samples = 3)

```

Identification

```{r echo=TRUE}

# Loading NIST 20 (*.msp) library
nist.database <- importMSP(filename = "E:/NIST_20_Library/Result/NIST20EI_2R.MSP",
                           DB.name = "NIST",
                           DB.version = "NIST20",
                           DB.info = "NIST_MS_Search_Export")
# Save library for a posterior faster loading
save(nist.database, file= "Data/Library/NIST20EI_2R.rda")
# Load R library
load("Data/Library/NIST20EI_2R.rda")
mslib <- nist.database
# Identification
ex <- identifyComp(ex,
                   id.database = mslib,
                   mz.range = NULL,
                   n.putative = 10)
# Identified compound
id.list <- idList(ex)
head(id.list[,1:4], n = 8)

```

Peak compound view

```{r echo=TRUE}

plotProfile(ex, 7)

```

Mirror plot of identified compounds

```{r echo=TRUE}

plotSpectra(ex, 7, 1, draw.color = "red")

```

Exporting spectra to NIST

```{r echo=TRUE}

export2MSP(ex,
           store.path = "Result/eRah_Result",
           alg.version = 2)

```

